"""Verify dataset, model, variable, and governance requirements.

This is an evidence-producing audit, not a data generator. It only reads
repository artifacts and the saved model, evaluates the saved model on a
freshly reconstructed group-safe held-out split, and writes a JSON report.
It never pads a dataset, duplicates records, changes labels, or claims that
an unmet target was achieved.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    top_k_accuracy_score,
)

BACKEND_DIR = Path(__file__).resolve().parents[1]
APP_DIR = BACKEND_DIR / "app"
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))
from verified_artifact import load_verified_joblib  # noqa: E402
PROJECT_DIR = BACKEND_DIR.parent
DATASET_DIR = BACKEND_DIR / "dataset"
PROCESSED_PATH = DATASET_DIR / "processed" / "merged_dataset.csv"
PROVENANCE_PATH = DATASET_DIR / "processed" / "row_provenance.csv"
MODEL_PATH = Path(
    os.getenv("MODEL_PATH", BACKEND_DIR / "models" / "disease_model.pkl")
).expanduser().resolve()
TRAINING_METRICS_PATH = Path(
    os.getenv(
        "TRAINING_METRICS_PATH",
        BACKEND_DIR / "models" / "training_metrics.json",
    )
).expanduser().resolve()
FEATURES_PATH = BACKEND_DIR / "models" / "disease_model_features.json"
ON_DEVICE_PATH = PROJECT_DIR / "assets" / "models" / "health_classifier_weights.json"
REPORT_PATH = BACKEND_DIR / "reports" / "ai_requirements_verification.json"
TARGET = "diseases"
TARGET_MIN = 150_000
TARGET_MAX = 200_000
ACCURACY_MIN = 0.95
ACCURACY_TARGET_MAX = 0.98


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _count_source(path: Path) -> dict[str, Any]:
    """Read a source file and record observable schema/quality facts."""
    suffix = path.suffix.lower()
    if suffix == ".csv":
        frame = pd.read_csv(path, low_memory=False)
        return {
            "path": str(path.relative_to(PROJECT_DIR)),
            "record_count": int(len(frame)),
            "column_count": int(len(frame.columns)),
            "columns": [str(column) for column in frame.columns],
            "missing_cell_count": int(frame.isna().sum().sum()),
            "exact_duplicate_rows": int(frame.duplicated().sum()),
        }
    return {
        "path": str(path.relative_to(PROJECT_DIR)),
        "record_count": None,
        "column_count": None,
        "columns": [],
        "missing_cell_count": None,
        "exact_duplicate_rows": None,
    }


def _source_inventory() -> list[dict[str, Any]]:
    """Inventory every dataset file kept in the repository."""
    paths = sorted(
        path
        for folder in (
            DATASET_DIR / "raw",
            DATASET_DIR / "text_datasets",
            DATASET_DIR / "excluded",
            DATASET_DIR / "knowledge_base",
            DATASET_DIR / "processed",
        )
        if folder.exists()
        for path in folder.iterdir()
        if path.is_file() and path.suffix.lower() in {".csv", ".json"}
    )
    records: list[dict[str, Any]] = []
    for path in paths:
        item = _count_source(path)
        relative = str(path.relative_to(PROJECT_DIR))
        if "/raw/" in relative:
            item.update(
                {
                    "role": "training_source_candidate",
                    "provider": "Not verified in repository metadata",
                    "reference": "Local file only; source URL, release, and license are not committed",
                    "data_type": "Structured tabular data; accepted only if binary symptom matrix",
                    "purpose": "Candidate source for disease classification training",
                    "reliability": "Schema-validated locally; external provenance and clinical representativeness remain unverified",
                }
            )
        elif "/processed/" in relative and path.name == "row_provenance.csv":
            item.update(
                {
                    "role": "provenance_sidecar",
                    "provider": "Generated by backend/scripts/merge_datasets.py",
                    "reference": "Source-row mapping for the canonical processed dataset",
                    "data_type": "Row-level provenance metadata",
                    "purpose": "Trace processed rows back to source file and source CSV row",
                    "reliability": "Reproducible locally; original publisher metadata remains inherited from source files",
                }
            )
        elif "/processed/" in relative:
            item.update(
                {
                    "role": "generated_training_artifact",
                    "provider": "Generated by backend/scripts/merge_datasets.py",
                    "reference": "Local deterministic pipeline and source files listed in this report",
                    "data_type": "Canonical binary symptom matrix",
                    "purpose": "Input to Random Forest training and evaluation",
                    "reliability": "Reproducible local artifact; inherits source provenance limitations",
                }
            )
        elif "/text_datasets/" in relative:
            item.update(
                {
                    "role": "reference_only",
                    "provider": "Not verified in repository metadata",
                    "reference": "Local file only; source URL, release, and license are not committed",
                    "data_type": "Free-text symptom narratives with labels",
                    "purpose": "Reference only; not accepted by the binary symptom trainer",
                    "reliability": "Not training-compatible without an approved, traceable conversion and validation",
                }
            )
        elif "/excluded/" in relative:
            item.update(
                {
                    "role": "excluded_from_training",
                    "provider": "Not verified in repository metadata",
                    "reference": "Local file only; source URL, release, and license are not committed",
                    "data_type": "Reference or low-sample disease/symptom data",
                    "purpose": "Retained for audit history; excluded by quality gates",
                    "reliability": "Not used for model training",
                }
            )
        else:
            item.update(
                {
                    "role": "reference_only",
                    "provider": "Project repository or not verified in repository metadata",
                    "reference": "Local file only; independent publisher/license metadata is not committed",
                    "data_type": "Knowledge-base or reference content",
                    "purpose": "Guidance/reference content; not supervised training rows",
                    "reliability": "Requires content review; not evidence of model performance",
                }
            )
        records.append(item)
    return records


def _fnv1a_32(text: str) -> int:
    value = 2166136261
    for byte in text.encode("utf-8"):
        value ^= byte
        value = (value * 16777619) & 0xFFFFFFFF
    return value


def _on_device_schema() -> dict[str, Any]:
    """Describe every input/output variable in the portable on-device model."""
    if not ON_DEVICE_PATH.exists():
        return {"status": "not_found", "path": str(ON_DEVICE_PATH)}
    payload = _load_json(ON_DEVICE_PATH)
    keywords = [str(value) for value in payload.get("feature_keywords", [])]
    bucket_map: dict[str, list[str]] = {}
    for keyword in keywords:
        bucket = 1 + (_fnv1a_32(keyword) % 50)
        bucket_map.setdefault(str(bucket), []).append(keyword)

    variables: list[dict[str, Any]] = [
        {
            "index": 0,
            "name": "age",
            "role": "X/input",
            "measures": "Patient age at time of record",
            "data_type": "float32",
            "possible_values": "non-negative age values normalized by /100",
            "encoding": "age / 100.0",
            "unit": "years",
            "source": "record age field",
        }
    ]
    for index in range(1, 51):
        variables.append(
            {
                "index": index,
                "name": f"keyword_hash_bucket_{index}",
                "role": "X/input",
                "measures": "Presence of one or more configured keywords in symptoms/details text",
                "data_type": "float32",
                "possible_values": [0.0, 1.0],
                "encoding": "FNV-1a 32-bit keyword hash modulo 50; presence is 1.0",
                "unit": None,
                "source_keywords": bucket_map.get(str(index), []),
            }
        )
    vital_variables = [
        (51, "blood_pressure_systolic", "Systolic blood pressure", "mmHg", "details BP sys/dia regex; /200"),
        (52, "blood_pressure_diastolic", "Diastolic blood pressure", "mmHg", "details BP sys/dia regex; /150"),
        (53, "temperature", "Body temperature", "degrees Celsius", "details Temp regex; /42"),
        (54, "heart_rate", "Heart rate", "beats per minute", "details HR regex; /200"),
    ]
    for index, name, measures, unit, encoding in vital_variables:
        variables.append(
            {
                "index": index,
                "name": name,
                "role": "X/input",
                "measures": measures,
                "data_type": "float32",
                "possible_values": "parsed non-negative numeric values after normalization",
                "encoding": encoding,
                "unit": unit,
                "source": "record details field",
            }
        )
    for index in range(55, int(payload.get("input_size", 200))):
        variables.append(
            {
                "index": index,
                "name": f"reserved_input_{index}",
                "role": "X/input/reserved",
                "measures": "No current variable; reserved capacity",
                "data_type": "float32",
                "possible_values": [0.0],
                "encoding": "always zero in current feature extractor",
                "unit": None,
                "source": "none",
            }
        )
    return {
        "status": "artifact_present_training_provenance_unverified",
        "path": str(ON_DEVICE_PATH.relative_to(PROJECT_DIR)),
        "input_size": int(payload.get("input_size", 0)),
        "input_variables": variables,
        "target_variables": [
            {
                "name": "category_output",
                "role": "y/target",
                "data_type": "categorical",
                "possible_values": payload.get("category_labels", []),
                "encoding": "softmax output; argmax label",
                "unit": None,
            },
            {
                "name": "severity_output",
                "role": "y/target",
                "data_type": "categorical",
                "possible_values": payload.get("severity_labels", []),
                "encoding": "softmax output; argmax label",
                "unit": None,
            },
        ],
        "training_dataset": {
            "record_count": None,
            "source": "Not verifiable from committed artifacts",
            "evaluation_metrics": None,
            "production_evidence_status": "insufficient; checked-in weights have no traceable training manifest or held-out metrics",
        },
    }


def _rf_feature_schema(
    features: pd.DataFrame,
    labels: pd.Series,
) -> dict[str, Any]:
    return {
        "model": "backend RandomForestClassifier",
        "X": [
            {
                "name": str(column),
                "role": "X/input feature",
                "measures": f"Presence or absence of normalized symptom '{column}'",
                "data_type": "uint8",
                "possible_values": [0, 1],
                "encoding": "1 = present; 0 = absent/not recorded in source row",
                "unit": None,
                "contribution": "One binary symptom input to the multi-class disease classifier",
            }
            for column in features.columns
        ],
        "y": {
            "name": TARGET,
            "role": "y/target",
            "measures": "Disease or condition label associated with the symptom vector",
            "data_type": "string categorical",
            "possible_values": sorted(str(value) for value in labels.unique()),
            "encoding": "Raw normalized string labels consumed by scikit-learn",
            "unit": None,
            "contribution": "Ground-truth class used for supervised training and evaluation",
        },
        "feature_count": int(features.shape[1]),
        "record_count": int(len(features)),
        "class_count": int(labels.nunique()),
    }


def _group_ids(features: pd.DataFrame) -> np.ndarray:
    packed = np.packbits(features.to_numpy(dtype="uint8"), axis=1)
    return np.array(
        [hashlib.blake2b(row.tobytes(), digest_size=16).hexdigest() for row in packed]
    )


def _near_duplicate_summary(features: pd.DataFrame) -> dict[str, Any]:
    """Count unique vectors that have an exact one-feature mutation present.

    This is an observed Hamming-distance-one diagnostic, not a record-removal
    rule. Near duplicates are retained because changing or merging them could
    alter the medical meaning of an input without evidence.
    """
    packed = np.packbits(
        features.to_numpy(dtype="uint8"),
        axis=1,
        bitorder="little",
    )
    values = [int.from_bytes(row.tobytes(), "little") for row in packed]
    counts = pd.Series(values, dtype="object").value_counts()
    unique_values = {int(value) for value in counts.index}
    near_values: set[int] = set()
    for value in unique_values:
        for bit in range(features.shape[1]):
            neighbour = value ^ (1 << bit)
            if neighbour in unique_values:
                near_values.add(value)
                near_values.add(neighbour)
    rows_in_near_groups = int(
        sum(int(counts.get(value, 0)) for value in near_values)
    )
    return {
        "hamming_distance": 1,
        "unique_vectors_with_hamming_distance_1_neighbor": int(
            len(near_values)
        ),
        "rows_in_hamming_distance_1_groups": rows_in_near_groups,
        "interpretation": "Diagnostic only; no near-duplicate rows were removed by this check.",
    }


def _confidence_diagnostics(
    labels: pd.Series,
    predictions: np.ndarray,
    probabilities: np.ndarray,
) -> dict[str, Any]:
    """Describe selective prediction behavior using held-out probabilities."""
    confidence = probabilities.max(axis=1)
    correct = predictions == labels.to_numpy()
    thresholds = []
    for threshold in (0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90):
        accepted = confidence >= threshold
        accepted_count = int(accepted.sum())
        thresholds.append(
            {
                "threshold": threshold,
                "accepted_records": accepted_count,
                "coverage": float(accepted.mean()),
                "accuracy_when_accepted": (
                    float(correct[accepted].mean()) if accepted_count else None
                ),
            }
        )
    return {
        "mean_max_probability": float(confidence.mean()),
        "median_max_probability": float(np.median(confidence)),
        "p05_max_probability": float(np.quantile(confidence, 0.05)),
        "p95_max_probability": float(np.quantile(confidence, 0.95)),
        "overall_correct_rate": float(correct.mean()),
        "threshold_analysis": thresholds,
        "policy_status": "evidence_only; no confidence threshold is activated in production",
        "safety_interpretation": "A probability score is not medical certainty; lower-confidence cases require professional review.",
    }


def _model_diagnostics(
    features: pd.DataFrame,
    labels: pd.Series,
    predictions: np.ndarray,
    probabilities: np.ndarray,
    model: Any,
) -> dict[str, Any]:
    class_labels = [str(value) for value in model.classes_]
    report = classification_report(
        labels,
        predictions,
        labels=class_labels,
        output_dict=True,
        zero_division=0,
    )
    matrix = confusion_matrix(labels, predictions, labels=class_labels)
    per_class = []
    for label in class_labels:
        values = report.get(label, {})
        per_class.append(
            {
                "disease": label,
                "precision": float(values.get("precision", 0.0)),
                "recall": float(values.get("recall", 0.0)),
                "f1": float(values.get("f1-score", 0.0)),
                "support": int(values.get("support", 0)),
            }
        )
    per_class.sort(key=lambda row: (row["recall"], row["f1"]))

    confusion_pairs = []
    for row_index, source in enumerate(class_labels):
        for column_index, predicted in enumerate(class_labels):
            count = int(matrix[row_index, column_index])
            if source != predicted and count:
                confusion_pairs.append(
                    {
                        "actual": source,
                        "predicted": predicted,
                        "count": count,
                    }
                )
    confusion_pairs.sort(key=lambda row: row["count"], reverse=True)

    feature_importance = []
    if hasattr(model, "feature_importances_"):
        order = np.argsort(model.feature_importances_)[::-1][:20]
        feature_importance = [
            {
                "feature": str(features.columns[index]),
                "importance": float(model.feature_importances_[index]),
                "definition": f"Presence or absence of normalized symptom '{features.columns[index]}'",
            }
            for index in order
        ]
    return {
        "lowest_recall_classes": per_class[:20],
        "top_confusion_pairs": confusion_pairs[:20],
        "feature_importance": feature_importance,
        "confidence": _confidence_diagnostics(labels, predictions, probabilities),
    }


def _provenance_quality(record_count: int) -> dict[str, Any]:
    if not PROVENANCE_PATH.exists():
        return {
            "status": "missing",
            "path": str(PROVENANCE_PATH.relative_to(PROJECT_DIR)),
        }
    provenance = pd.read_csv(PROVENANCE_PATH, low_memory=False)
    required = {
        "processed_row_index",
        "normalized_disease",
        "source_file",
        "source_csv_row_number",
    }
    missing_columns = sorted(required - set(provenance.columns))
    return {
        "status": "valid" if not missing_columns else "invalid",
        "path": str(PROVENANCE_PATH.relative_to(PROJECT_DIR)),
        "record_count": int(len(provenance)),
        "matches_processed_record_count": bool(len(provenance) == record_count),
        "missing_columns": missing_columns,
        "missing_cell_count": int(provenance.isna().sum().sum()),
        "unique_processed_row_indexes": int(
            provenance["processed_row_index"].nunique()
        )
        if "processed_row_index" in provenance
        else None,
        "source_row_counts": (
            provenance["source_file"].value_counts().sort_index().to_dict()
            if "source_file" in provenance
            else {}
        ),
    }


def _evaluate_saved_model(
    features: pd.DataFrame,
    labels: pd.Series,
    model: Any,
) -> dict[str, Any]:
    """Evaluate the saved artifact on the same group-safe split it was trained on."""
    from train import group_safe_split  # pylint: disable=import-outside-toplevel

    groups = _group_ids(features)
    train_idx, test_idx = group_safe_split(features, labels, groups)
    x_test = features.iloc[test_idx]
    y_test = labels.iloc[test_idx]
    predictions = model.predict(x_test)
    probabilities = model.predict_proba(x_test)
    overlap = len(set(groups[train_idx]).intersection(set(groups[test_idx])))
    return {
        "method": "StratifiedGroupKFold(n_splits=5) first fold; groups=identical_feature_vector",
        "train_records": int(len(train_idx)),
        "test_records": int(len(test_idx)),
        "train_test_feature_vector_overlap_groups": int(overlap),
        "accuracy": float(accuracy_score(y_test, predictions)),
        "balanced_accuracy": float(balanced_accuracy_score(y_test, predictions)),
        "precision_weighted": float(precision_score(y_test, predictions, average="weighted", zero_division=0)),
        "recall_weighted": float(recall_score(y_test, predictions, average="weighted", zero_division=0)),
        "f1_weighted": float(f1_score(y_test, predictions, average="weighted", zero_division=0)),
        "precision_macro": float(precision_score(y_test, predictions, average="macro", zero_division=0)),
        "recall_macro": float(recall_score(y_test, predictions, average="macro", zero_division=0)),
        "f1_macro": float(f1_score(y_test, predictions, average="macro", zero_division=0)),
        "top2_accuracy": float(top_k_accuracy_score(y_test, probabilities, k=2, labels=model.classes_)),
        "top3_accuracy": float(top_k_accuracy_score(y_test, probabilities, k=3, labels=model.classes_)),
        "diagnostics": _model_diagnostics(
            x_test,
            y_test,
            predictions,
            probabilities,
            model,
        ),
    }


def build_report() -> dict[str, Any]:
    if not PROCESSED_PATH.exists():
        raise FileNotFoundError(f"Missing processed dataset: {PROCESSED_PATH}")
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Missing saved model: {MODEL_PATH}")

    frame = pd.read_csv(PROCESSED_PATH, low_memory=False)
    if TARGET not in frame.columns:
        raise ValueError(f"Missing target column '{TARGET}' in {PROCESSED_PATH}")
    features = frame.drop(columns=[TARGET])
    labels = frame[TARGET].astype("string")
    groups = _group_ids(features)
    grouped = pd.DataFrame({"group": groups, "label": labels.to_numpy()})
    group_sizes = grouped.groupby("group").size()
    label_counts = grouped.groupby("group")["label"].nunique()
    conflict_groups = label_counts[label_counts > 1]
    expected_sha256 = str(
        _load_json(TRAINING_METRICS_PATH).get("model_sha256", "")
    )
    model = load_verified_joblib(MODEL_PATH, expected_sha256)
    evaluation = _evaluate_saved_model(features, labels, model)
    feature_prevalence = features.mean().sort_values()
    training_metrics = (
        _load_json(TRAINING_METRICS_PATH)
        if TRAINING_METRICS_PATH.exists()
        else {}
    )

    source_inventory = _source_inventory()
    scale_status = TARGET_MIN <= len(features) <= TARGET_MAX
    accuracy_status = evaluation["accuracy"] >= ACCURACY_MIN
    report = {
        "generated_at": pd.Timestamp.now(tz="UTC").isoformat(),
        "report_purpose": "Actual repository evidence for additional AI system requirements",
        "integrity_statement": "No records were duplicated, synthetically padded, relabeled, or fabricated by this verifier.",
        "dataset_scale": {
            "target_min_records": TARGET_MIN,
            "target_max_records": TARGET_MAX,
            "verified_valid_training_records": int(len(features)),
            "status": "met" if scale_status else "not_met",
            "shortfall_to_minimum": max(TARGET_MIN - len(features), 0),
            "training_eligible_sources": [
                item["path"]
                for item in source_inventory
                if item.get("role") == "training_source_candidate"
            ],
            "expansion_policy": "Acquire and document additional real, compatible, licensed/consented records; never duplicate or synthesize to reach the range.",
        },
        "dataset_quality": {
            "record_count": int(len(frame)),
            "feature_count": int(features.shape[1]),
            "class_count": int(labels.nunique()),
            "missing_cell_count": int(frame.isna().sum().sum()),
            "blank_target_count": int(labels.str.strip().eq("").sum()),
            "exact_duplicate_rows": int(frame.duplicated().sum()),
            "unique_feature_vector_groups": int(group_sizes.size),
            "rows_sharing_feature_vector": int(group_sizes[group_sizes > 1].sum()),
            "label_conflict_groups": int(conflict_groups.size),
            "rows_in_label_conflict_groups": int(
                grouped["group"].isin(conflict_groups.index).sum()
            ),
            "all_feature_values_binary": bool(
                set(features.to_numpy().ravel().tolist()).issubset({0, 1})
            ),
            "feature_names_unique": not bool(features.columns.duplicated().any()),
            "class_size_min": int(labels.value_counts().min()),
            "class_size_max": int(labels.value_counts().max()),
            "class_distribution": {
                str(label): int(count)
                for label, count in labels.value_counts().sort_index().items()
            },
            "constant_feature_count": int(
                (features.nunique(dropna=False) <= 1).sum()
            ),
            "near_zero_variance_feature_count": int(
                ((feature_prevalence <= 0.0005)
                 | (feature_prevalence >= 0.9995)).sum()
            ),
            "feature_prevalence_min": float(feature_prevalence.min()),
            "feature_prevalence_max": float(feature_prevalence.max()),
            "near_duplicate_analysis": _near_duplicate_summary(features),
        },
        "provenance": _provenance_quality(len(features)),
        "dataset_sources": source_inventory,
        "variables": {
            "random_forest": _rf_feature_schema(features, labels),
            "on_device_classifier": _on_device_schema(),
        },
        "model_evaluation": {
            **evaluation,
            "cross_validation": training_metrics.get("cross_validation"),
            "accuracy_target_minimum": ACCURACY_MIN,
            "accuracy_target_range": [ACCURACY_MIN, ACCURACY_TARGET_MAX],
            "accuracy_status": "met" if accuracy_status else "not_met",
            "interpretation": "Held-out dataset performance only; not clinical validation or certification.",
        },
        "iso_alignment": {
            "status": "documented_controls_not_certification",
            "reference_document": "docs/ISO_ALIGNMENT.md",
            "certification_claim": False,
            "standards": [
                "ISO/IEC 25010:2023",
                "ISO/IEC 27001:2022",
                "ISO/IEC 23894:2023",
                "ISO/IEC 42001:2023",
                "ISO/IEC TR 24027:2021",
            ],
        },
        "requirements_status": {
            "dataset_scale": scale_status,
            "algorithm_training_validation_testing": evaluation[
                "train_test_feature_vector_overlap_groups"
            ]
            == 0,
            "accuracy_minimum_95_percent": accuracy_status,
            "variables_defined": True,
            "sources_documented": all(
                item.get("provider") and item.get("reference")
                for item in source_inventory
            ),
            "data_quality_gates": bool(
                frame.duplicated().sum() == 0
                and frame.isna().sum().sum() == 0
                and set(features.to_numpy().ravel().tolist()).issubset({0, 1})
            ),
            "iso_alignment_documented": True,
        },
    }
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 when scale or accuracy acceptance targets are not met.",
    )
    args = parser.parse_args()
    sys.path.insert(0, str(BACKEND_DIR / "app"))
    report = build_report()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps({
        "report": str(REPORT_PATH),
        "verified_records": report["dataset_scale"]["verified_valid_training_records"],
        "held_out_accuracy": report["model_evaluation"]["accuracy"],
        "scale_status": report["dataset_scale"]["status"],
        "accuracy_status": report["model_evaluation"]["accuracy_status"],
    }, indent=2))
    if args.strict and (
        report["dataset_scale"]["status"] != "met"
        or report["model_evaluation"]["accuracy_status"] != "met"
    ):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
